package com.pm.aiservice.model;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.LocalDateTime;
import java.util.Map;

@Data
@NoArgsConstructor
@AllArgsConstructor
public class PatientEvent {
    private String eventId;
    private String eventType; // "patient.created", "note.created", "vitals.updated"
    private String patientId;
    private String sourceServiceId;
    private Map<String, Object> eventData;
    private LocalDateTime timestamp;
    
    // Getters and setters will be generated by Lombok @Data annotation
    public String getPatientId() {
        return patientId;
    }
    
    public String getEventType() {
        return eventType;
    }
    
    public String getSourceServiceId() {
        return sourceServiceId;
    }
    
    public Map<String, Object> getEventData() {
        return eventData;
    }
}
